black-fu/config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :news
  resources :barcodes
  resources :products
  resources :companies
get "/", to:"companyhomepage#index"

end

black-fu/app/models/barcode.rb
class Barcode < ActiveRecord::Base
end

black-fu/app/controllers/barcodes_controller.rb
class BarcodesController < ApplicationController
  before_action :set_barcode, only: [:show, :edit, :update, :destroy]

  # GET /barcodes
  # GET /barcodes.json
  def index
    @barcodes = Barcode.all
  end

  # GET /barcodes/1
  # GET /barcodes/1.json
  def show
  end

  # GET /barcodes/new
  def new
    @barcode = Barcode.new
  end

  # GET /barcodes/1/edit
  def edit
  end

  # POST /barcodes
  # POST /barcodes.json
  def create
    @barcode = Barcode.new(barcode_params)

    respond_to do |format|
      if @barcode.save
        format.html { redirect_to @barcode, notice: 'Barcode was successfully created.' }
        format.json { render :show, status: :created, location: @barcode }
      else
        format.html { render :new }
        format.json { render json: @barcode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /barcodes/1
  # PATCH/PUT /barcodes/1.json
  def update
    respond_to do |format|
      if @barcode.update(barcode_params)
        format.html { redirect_to @barcode, notice: 'Barcode was successfully updated.' }
        format.json { render :show, status: :ok, location: @barcode }
      else
        format.html { render :edit }
        format.json { render json: @barcode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /barcodes/1
  # DELETE /barcodes/1.json
  def destroy
    @barcode.destroy
    respond_to do |format|
      format.html { redirect_to barcodes_url, notice: 'Barcode was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_barcode
      @barcode = Barcode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def barcode_params
      params.require(:barcode).permit(:no)
    end
end

black-fu/app/helpers/barcodes_helper.rb
module BarcodesHelper
end

black-fu/app/views/barcodes/_form.html.erb
<%= form_for(@barcode) do |f| %>
  <% if @barcode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@barcode.errors.count, "error") %> prohibited this barcode from being saved:</h2>

      <ul>
      <% @barcode.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :no %><br>
    <%= f.text_field :no %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

black-fu/app/views/barcodes/edit.html.erb
<h1>Editing Barcode</h1>

<%= render 'form' %>

<%= link_to 'Show', @barcode %> |
<%= link_to 'Back', barcodes_path %>

black-fu/app/views/barcodes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Barcodes</h1>

<table>
  <thead>
    <tr>
      <th>No</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @barcodes.each do |barcode| %>
      <tr>
        <td><%= barcode.no %></td>
        <td><%= link_to 'Show', barcode %></td>
        <td><%= link_to 'Edit', edit_barcode_path(barcode) %></td>
        <td><%= link_to 'Destroy', barcode, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Barcode', new_barcode_path %>

black-fu/app/views/barcodes/new.html.erb
<h1>New Barcode</h1>

<%= render 'form' %>

<%= link_to 'Back', barcodes_path %>

black-fu/app/views/barcodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>No:</strong>
  <%= @barcode.no %>
</p>

<%= link_to 'Edit', edit_barcode_path(@barcode) %> |
<%= link_to 'Back', barcodes_path %>