black-fu/config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :news
  resources :barcodes
  resources :products
  resources :companies
get "/", to:"companyhomepage#index"

end

black-fu/app/models/company.rb
class Company < ActiveRecord::Base
  mount_uploader :logo, ProductsPhotoUploader
end

black-fu/app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :ceo, :logo)
    end
end

black-fu/app/helpers/companies_helper.rb
module CompaniesHelper
end

black-fu/app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :ceo %><br>
    <%= f.text_field :ceo %>
  </div>
  <div class="field">
    <%= f.label :logo %><br>
    <%= f.file_field :logo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

black-fu/app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

black-fu/app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<div class="header">
  <div id="logo"></div>
  <div class="title"></div>
  <div class="navbar">
    <div class="line-box">
      <button class="btn btn-default active" type="submit" id="company-bt">企業 Company</button>
      <button class="btn btn-default" type="submit" id="product-bt">商品 Product</button>
      <button class="btn btn-default" type="submit" id="news-bt">新聞 News</button>
    </div>
  </div>
</div>

<div id="company-contents">
  <% @companies.each do |company| %>
  <div class="company-box">
    <div class="name-box">
      <%= company.name %>
    </div>
    <div class="logo-box">
      <div class="img-div">
        <%= image_tag company.logo.prod_min_img %>
      </div>

    </div>
    <div class="ceo-box">
      <%= company.ceo %>
    </div>
  </div>
  <% end %>
</div>

black-fu/app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

black-fu/app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Ceo:</strong>
  <%= @company.ceo %>
</p>

<p>
  <strong>Logo:</strong>
  <%= @company.logo %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>