black-fu/config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :news
  resources :barcodes
  resources :products
  resources :companies
get "/", to:"companyhomepage#index"

end

black-fu/app/models/news.rb
class News < ActiveRecord::Base
  mount_uploader :nimg, ProductsPhotoUploader
end

black-fu/app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]

  # GET /news
  # GET /news.json
  def index
    @news = News.all
  end

  # GET /news/1
  # GET /news/1.json
  def show
  end

  # GET /news/new
  def new
    @news = News.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(news_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to news_index_url, notice: 'News was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params.require(:news).permit(:title, :content, :nimg, :postdate, :from, :url)
    end
end

black-fu/app/helpers/news_helper.rb
module NewsHelper
end

black-fu/app/views/news/_form.html.erb
<%= form_for(@news) do |f| %>
  <% if @news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
      <% @news.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :nimg %><br>
    <%= f.file_field :nimg %>
  </div>
  <div class="field">
    <%= f.label :postdate %><br>
    <%= f.text_field :postdate %>
  </div>
  <div class="field">
    <%= f.label :from %><br>
    <%= f.text_field :from %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

black-fu/app/views/news/edit.html.erb
<h1>Editing News</h1>

<%= render 'form' %>

<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_index_path %>

black-fu/app/views/news/index.html.erb
<p id="notice"><%= notice %></p>

<div class="header">
  <div id="logo"></div>
  <div class="title"></div>
  <div class="navbar">
    <div class="line-box">
      <button class="btn btn-default" type="submit" id="company-bt">企業 Company</button>
      <button class="btn btn-default" type="submit" id="product-bt">商品 Product</button>
      <button class="btn btn-default active" type="submit" id="news-bt">新聞 News</button>
    </div>
  </div>
</div>

<table class="table table-hover news-list">
  <tbody>
    <% @news.order("postdate DESC").each do |news| %>
      <tr>
        <td style="vertical-align: middle; text-align: center;" ><%= image_tag news.nimg.prod_min_img %></td>
        <td style="vertical-align: middle;"><h4>
          <%= link_to news.title, news %>
        </h4></td>
        <td style="vertical-align: middle;"><%= news.postdate %></td>
        <td style="vertical-align: middle;"><%= news.from %></td>
      </tr>
    <% end %>
  </tbody>
</table>

black-fu/app/views/news/new.html.erb
<h1>New News</h1>

<%= render 'form' %>

<%= link_to 'Back', news_index_path %>

black-fu/app/views/news/show.html.erb
<p id="notice"><%= notice %></p>
<div class="header">
  <div id="logo"></div>
  <div class="title"></div>
  <!-- <div class="navbar">
    <ul>
      <li class="active" id="news-bt">新聞 News</li>
      <li id="product-bt">商品 Product</li>
      <li id="company-bt">企業 Company</li>
    </ul>
  </div> -->
</div>

<span class="n-title"><%= @news.title %></span>
<span class="n-date"><%= @news.postdate %></span>
<span class="n-from">出處：<b><%= @news.from %></b></span>

<div class="news-content">
  <span class="img-thumbnail n-img"><%= image_tag @news.nimg.news_min_img %></span>
  <p id="n-cont"><%= @news.content %></p>
</div>

<div class="width-full">
  <%= link_to '資料來源', @news.url, :target => "_blank" %>
</div>

<!-- <%= link_to 'Edit', edit_news_path(@news) %> | -->
<button type="button" class="btn btn-info fow"><%= link_to '回列表', news_index_path %></button>